import { PRMetadata, SafetyCheckResult, TestResult } from '../core/types.js';

export interface PrBodyInput {
  summary: string;
  rootCause: string;
  fixSummary: string;
  changedFiles: string[];
  testResult: TestResult;
  safety: SafetyCheckResult;
  metadata: PRMetadata;
}

export function generatePrBody(input: PrBodyInput): string {
  return [
    '## Summary',
    input.summary,
    '',
    '## Root Cause',
    input.rootCause,
    '',
    '## Fix',
    input.fixSummary,
    '',
    '## Files Changed',
    ...input.changedFiles.map((file) => `- ${file}`),
    '',
    '## Validation',
    `- Command: \`${input.testResult.command}\``,
    `- Result: ${input.testResult.passed ? 'passed' : 'failed'} (${input.testResult.exitCode ?? 'no exit code'})`,
    `- Duration: ${input.testResult.durationMs}ms`,
    '',
    '## Safety Checks',
    `- Modified file count: ${input.safety.changedFiles.length}`,
    `- Forbidden file check: ${input.safety.forbiddenFiles.length === 0 ? 'passed' : 'failed'}`,
    `- Dry run: ${input.metadata.dryRun ? 'yes' : 'no'}`,
    input.safety.warnings.length > 0 ? `- Warnings: ${input.safety.warnings.join('; ')}` : '- Warnings: none',
    '',
    '## DevLoop Metadata',
    `- Attempt count: ${input.metadata.attempts}`,
    `- Provider: ${input.metadata.provider}`,
    `- Model: ${input.metadata.model}`,
    '- generated by DevLoop AI'
  ].join('\n');
}
