import { describe, expect, test } from 'vitest';
import { generatePrBody } from './pr-body.js';

describe('generatePrBody', () => {
  test('includes root cause, fix, validation, safety, and metadata', () => {
    const body = generatePrBody({
      summary: 'Fix add implementation.',
      rootCause: 'The add function subtracted values.',
      fixSummary: 'Changed subtraction to addition.',
      changedFiles: ['index.js'],
      testResult: {
        command: 'npm test',
        exitCode: 0,
        stdout: 'pass',
        stderr: '',
        durationMs: 123,
        passed: true,
        timedOut: false
      },
      safety: {
        passed: true,
        errors: [],
        warnings: [],
        changedFiles: ['index.js'],
        forbiddenFiles: []
      },
      metadata: {
        attempts: 1,
        provider: 'openai',
        model: 'gpt-4.1-mini',
        dryRun: false
      }
    });

    expect(body).toContain('## Root Cause');
    expect(body).toContain('index.js');
    expect(body).toContain('npm test');
    expect(body).toContain('generated by DevLoop AI');
  });
});
