import { describe, expect, test } from 'vitest';
import { decodeTextBuffer } from './text-file.js';

describe('decodeTextBuffer', () => {
  test('decodes UTF-16LE logs generated by Windows PowerShell redirection', () => {
    const buffer = Buffer.from('AssertionError [ERR_ASSERTION]', 'utf16le');

    expect(decodeTextBuffer(buffer)).toBe('AssertionError [ERR_ASSERTION]');
  });

  test('removes UTF-8 byte order marks from patch files', () => {
    const buffer = Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from('--- a/index.js')]);

    expect(decodeTextBuffer(buffer)).toBe('--- a/index.js');
  });
});
